### ISSUE TITLE
View channel map subscription per snap

### ISSUE THREAD

**Issue by therealjuan** [canonical-websites/snapcraft.io#1052]
On the metrics of a snap, publishers might benefit from seeing a data visualization of their snaps. 

Since the `latest/stable` channel will the main for ~95% (or more) of all snaps, it will be good to showcase all channel maps logarithmically as the numbers will be radically extreme and hard to decipher. Something similar to what has been done with snap adoption per country. The idea is not to showcase a bad representation of data but to help understand and read the data.

This metric can also be showcased in a monthly publishers' report that we will send about updates on the platform.

**Comment by matthewpaulthomas** [comment]
A snap’s Metrics page already has a visualisation of weekly active devices per channel. So if a logarithmic scale would help, maybe this could be a toggle above the existing chart: “Linear scale” (the default) vs. “Logarithmic scale”. Or maybe the existing segmentation menu could have an extra item: the existing “By channel” followed by “By channel (logarithmic)”.

However, that view shouldn’t be stacked like all the other views, because stacking would be misleading — a smaller segment would often represent many more devices than a larger segment.

**Comment by therealjuan** [comment]
Apart from time-related graphs, it will be good to display the different channels as our current channel map using bar charts logarithmically. This will help publishers understand the current adoption of the different channels at that precise moment in time.

**Comment by shivjoshi1996** [comment]
@therealjuan Could you please estimate this :)

**Comment by Lukewh** [comment]
I need a picture to understand this.

**Comment by therealjuan** [comment]
We will be discussing further metric improvements during this cycle so closing until we have a better idea on how to improve them
