### ISSUE TITLE
Misaligned heading and button

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-websites/snapcraft.io#1198]
### Expected behaviour
The button needs to be positioned .5rem lower to align well.
### Steps to reproduce the problem
<img width="1074" alt="screen shot 2018-10-10 at 17 03 45" src="https://user-images.githubusercontent.com/2741678/46749895-9de1d900-ccae-11e8-9a48-42b1c6af3527.png">

### Specs

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by matthewpaulthomas** [comment]
That heading and button should no longer exist at all: it’s redundant with the first-snap flow immediately above.

That said, it looks much better than that for me, in Chromium on Ubuntu:

![snapcraft io 1198-heading-button](https://user-images.githubusercontent.com/19801137/46790998-0e810800-cd38-11e8-8844-9c679ca7178d.png)

If it was still a problem, maybe it would be possible to vertically center the button on the heading, or to align the bottom of the button with the baseline of the heading, rather than making manual adjustments.

**Comment by bartaz** [comment]
@lyubomir-popov In what browser you see this problem?

Seems to be fine in Chrome/Firefox on MacOS:

<img width="923" alt="screen shot 2018-10-11 at 10 51 23" src="https://user-images.githubusercontent.com/83575/46792485-c667e280-cd43-11e8-844a-170a6a931243.png">

Buttons is explicitly vertically centered (with vanilla util), which is visible on smaller width:

<img width="783" alt="screen shot 2018-10-11 at 10 51 40" src="https://user-images.githubusercontent.com/83575/46792514-d8498580-cd43-11e8-9626-7bbd8ac9561d.png">

**Comment by lyubomir-popov** [comment]
@bartaz Chrome. Looking at your screenshot, it is exactly as in mine - a bit higher than it should be to look perfectly aligned. I had a .5rem nudge at the top with the u-sv1 utility I think.

**Comment by lyubomir-popov** [comment]
@bartaz Sorry just looked at it again and it is ok. NOt sure what was going on when I took the screenshot. CLosing this
