### ISSUE TITLE
Add search capability to the blog

### ISSUE THREAD

**Issue by kyrofa** [canonical-websites/snapcraft.io#1220]
Right now the only way for me to find blog posts from the past to send to clients is to go to google and use "site:". Would be great to have the ability to search from snapcraft.io/blog instead.

**Comment by therealjuan** [comment]
What needs to happen for site-wide search in snapcraft.io? This starts to feel needed as it can be enabled in docs and blog, as well as probably other sites that might benefit from this solution. It will be good to get an estimate.

For the layout is pretty simple and we can implement something similar to what we have in docs but I  would argue that since docs have more content to search for, it is not as urgent at this point in time to enable search in the blog section. 

Just to be clear, sending people to ubuntu.com for searching content through blog or docs could damage perception on the product and disable the whole cross-distro story.

**Comment by nottrobin** [comment]
Okay then, so it's about an iteration of work. So all we need to decide is how high it is in Snapcraft's back-end priorities.

**Comment by therealjuan** [comment]
We can plan it to be done maybe in the first viable iteration on the new year as some of the features we are planning next will depend on discussions during the upcoming roadmap sprint. Let me know if you want further details or if we need to be more explicit about back-end requirements going forward.

**Comment by evandandrea** [comment]
>We also have the option of, in the interim, providing the same search solution we have on https://docs.snapcraft.io/ which points to https://www.ubuntu.com/search. This would be much quicker to implement (probably 3-5 points).

Please do not do this. Pointing the docs search at ubuntu.com makes snapcraft.io feel like an Ubuntu project, which it is not. It compromises the cross-distribution story behind snaps.

**Comment by therealjuan** [comment]
This will be done by the base squad some time after Malta. Thanks!
