### ISSUE TITLE
Code font size is too big

### ISSUE THREAD

**Issue by kyrofa** [canonical-websites/snapcraft.io#1221]
The code sections use a font size even bigger than the text sections, which makes it really difficult to put a reasonable amount of code in there without word-wrapping:

![screenshot from 2018-10-18 10-37-57](https://user-images.githubusercontent.com/946674/47173088-f7a35e00-d2c1-11e8-94a4-af78b2694784.png)

This problem is exacerbated by the fact that the [layout on the Ubuntu blog is even narrower](https://github.com/canonical-websites/blog.ubuntu.com/issues/415).

**Comment by fitojb** [comment]
Shouldn't the page be using the Ubuntu Mono font there? Perhaps the size was set as big as it is because they took into account that Ubuntu Mono is smaller than most monospaced fonts (it was modelled after Inconsolata).

**Comment by kyrofa** [comment]
> [T]he font-size of `<pre>` and `<code>` tags shouldn't differ from the paragraph font size[.] [...] To be sure, could you please add a link to the blogpost so I can verify this is the case?

Of course. I think your analysis is correct. Here's [one on the snapcraft blog](https://snapcraft.io/blog/ros-production-our-prototype), and here's the same [one on the ubuntu blog](https://blog.ubuntu.com/2017/04/13/ros-production-our-prototype). I'd like to call your attention particularly to the launch file, which is immediately preceded by the text "Finally, we’re also going to include the random walker launch file so that launching this single launch file brings up our entire prototype" (for your searching). This was originally formatted to fit on the Insights blog.

> Separately, there's a question of whether we should reduce the code snippet font size in vanilla to allow more code to be visible

That's really the question I intended to raise here.

**Comment by fitojb** [comment]
(Note that the screenshots in this thread feature DejaVu Sans Mono, not Ubuntu Mono.)

**Comment by lyubomir-popov** [comment]
@kyrofa we have yet to discuss this in the vanilla working group, but there seems to be a related "solution" proposed in another issue - which makes the snippet scroll horizontally instead of wrapping. Would that be an acceptable compromise? Or do you expect to be able to see say 80 characters?
Asking as changing font size or site width will both have wider implications. For example, for an inline one word snippet you'd have different font sizes on the same row. 

@fitojb you're right, it is defaulting to the user agent font-family, which will be different depending on browser. This is because the markup differs from what vanilla is expecting (no nested ```<code>``` inside the ```pre```s). I've filed a bug for that:
https://github.com/vanilla-framework/vanilla-framework/issues/2037
