### ISSUE TITLE
Cache `images/badges` for a year

### ISSUE THREAD

**Issue by Lukewh** [canonical-websites/snapcraft.io#1302]
The badges won't change, they'll only be added to. We should ensure that they're cached heavily.

See https://github.com/canonical-websites/snapcraft.io/pull/1284

**Comment by shivjoshi1996** [comment]
@tbille Can you estimate this please

**Comment by nottrobin** [comment]
To close the loop a bit in this ticket - we discussed this at length in https://github.com/canonical-websites/snapcraft.io/pull/1335. The high-level outcomes are:

- There's risk to giving the badges year-long caches in their current place in snapcraft.io, because it would then be paramount that their content didn't change in-place, but there's nothing in snapcraft.io's structure or implementation to enforce that
- It's also generally undesirable to have one URL under `/static` behave fundamentally differently from all the others
- We don't actually know how important caching is for these badges - so we've put some metrics in place so we can get an idea of the traffic we're talking about here
- If we need to provide year-long caches for performance & reliability, the preferred solution is to make the current assets.ubuntu.com service available also at assets.canonical.com, and then host the badges there instead of snapcraft.io (which has year-long caches by default)
