### ISSUE TITLE
Release UI: Trigger devmode warnings after promoting devmode release/s

### ISSUE THREAD

**Issue by therealjuan** [canonical-websites/snapcraft.io#1342]
Right now if we look at snaps with releases on `devmode` we are showcasing a global warning and a warning next to each release:

![image.png](https://images.zenhubusercontent.com/56b0a0916caf56c9d38c2685/dda32c96-a47a-4c64-9fff-f7e38af654fe)

To avoid the interface to look like the publisher has done something wrong (as they haven't done anything yet) to show the warning once a publisher tries to promote release/s set in `devmode` to a `stable` or `candidate` channel

There is a separate issue to raise which is to include additional text and context on the release UI so publishers understand what can be done and therefore understand the interface.

**(From snapju workshop)**

**Comment by bartaz** [comment]
@therealjuan what do you mean by 'once a publisher tries to promote release/s set in devmode to a stable or candidate channel'?

It is not possible to promote devmode snap to these channels. They were not available to select or now (#1350) are disabled. So publishers can't 'try' to promote them.

We can of course change that and allow them to select these devmode revisions to stable/candidate, but should we do it just to show them warning that they can't?

Maybe tooltips that we have on devmode icons are enough, and we can just drop the top page warning? Or we can stop using warning notification style and use info (which will be less alarming)?
Also - having some custom devmode icon instead of Vanilla warning one could help.

**Comment by matthewpaulthomas** [comment]
Now that `candidate` and `stable` appear as disabled items, rather than being hidden altogether, one possibility (as I suggested on IRC) would be to explain the situation when hovering or clicking on the disabled items. For example, in a box that floats alongside the menu.

**Comment by bartaz** [comment]
@therealjuan Since it was reported we changed the icon of devmode and moved the notification inside the history panels. Is there anything else we want to do with this?

**Comment by therealjuan** [comment]
Because of the recent changes in this prior its report, we can include the same tooltip on the disabled menu items when promoting channels. 

The content of the tooltip is `Revisions in with grade devel cannot be released to stable or candidate channels`

![image](https://user-images.githubusercontent.com/8167677/51022660-c95db380-157c-11e9-94e6-ed39a067961e.png)
