### ISSUE TITLE
Store page suggestion: Alignment of search button and category scroll button

### ISSUE THREAD

**Issue by igorljubuncic** [canonical-websites/snapcraft.io#1447]
The search box is aligned to horizontal page divider. The circular scroll more buttons (>) are not aligned to either the bar or the search box.

Expected behavior (unless intentional): the search box and the scroll buttons should be aligned.

![store-button-alignment](https://user-images.githubusercontent.com/43789966/49998085-3a647800-ff8b-11e8-9f1c-c9030ed9ca1b.png)

**Comment by matthewpaulthomas** [comment]
I think this is deliberate: the scroll button overhangs the scroll area by 50%. That is, the center of the button is aligned with the end of the search button and dividers. The same happens for snaps with several screenshots, where the scroll buttons overhang the screenshot carousel by 50%.

![1447-snapcraft io-scrollbutton-overhang](https://user-images.githubusercontent.com/19801137/50333989-d1d34900-04fe-11e9-91e4-2b6097055da2.png)

However, while it might be intentional, it might still be suboptimal: in snap carousels, it can almost completely cover the snap name.
 
![1447-snapcraft io-scrollbutton-occlusion](https://user-images.githubusercontent.com/19801137/50334266-a69d2980-04ff-11e9-9335-9ee9e39af1c6.png)

**Comment by therealjuan** [comment]
We are planning on updating the store homepage carousel arrows as part of the Magazine View piece of work so this is closing. Thanks
