### ISSUE TITLE
Release UI – Filter unassigned revisions

### ISSUE THREAD

**Issue by therealjuan** [canonical-websites/snapcraft.io#1473]
To help publishers reduce the amount of clicks and selection to do with revisions relevant for them, we will add a contextual menu on unassigned revisions to help with choices.

**Contextual menu options**

![image](https://user-images.githubusercontent.com/8167677/50152583-e4aa0b80-02bb-11e9-8396-542f7e6ce4d9.png)

Filter revisions
* **Recent revisions** – Revisions with most recent unassigned version not released and up to a week old will be shown here.
* **Unreleased revisions** – Revisions not released ever to any channel will appear in this list.
* **All revisions** – All revisions released or not from all tracks will be shown in the list.

This panel will work similarly to a contextual menu but will include a description tagline below the title.

**Comment by matthewpaulthomas** [comment]
Maybe it’s just lack of coffee, but I‘m having trouble understanding the first and third captions …  What’s the difference between “unassigned” and “not released”? And does “not from all tracks” mean “from some tracks”, or something else?

This is a case where tuning the text really affects the design: if there was a way to explain each option in a few words, it could be a simpler `<select>` instead. For example, would it work to have just “Show revisions: [ All / Never released / Never released from past week ]”?

If that’s not possible, two other ways to shorten the text: drop the word “revisions” from each label, and drop the “will…” phrase from each caption (~~will be shown~~, ~~will appear in this list~~, ~~will be shown in the list~~).

**Comment by therealjuan** [comment]
@matthewpaulthomas that's a good point thinking about it, maybe this is a case of having over-designed the solution. How about having the select dropdown for now...

```
Show revisions...
      Never released from past week
      Never released
      All revisions (released or not)```

The order is important here as we would like to make `never released from past week` as the default one so whenever you land on the `releases` section is to promote revisions across channels.

The main idea is that in the near future we willl be adding more options to the dropdown (CIs, settings, customised elements...) but since that is not needed for now, it is a good call to just start simple for now.

@bartaz thoughts?

**Comment by bartaz** [comment]
We already dropped the 'revisions', because we have it in the heading. So our current version is this:

<img width="561" alt="screenshot 2019-01-07 at 11 59 29" src="https://user-images.githubusercontent.com/83575/50764669-c78daa80-1273-11e9-9d76-263eeed69f23.png">

What we want to do is to iterate on that.

The UI issue to consider is that there is not a lot of space in the dropdown select button for a long label, so that's why we want to give more context in the dropdown itself.

@therealjuan "Never released from past week" is quite long (and for sure wont fit in our current width of the select. Unless we keep it as 'Recent' and use "Never released from past week" as an additional description. Still "Never released from past week" seems to read strange. I know that it's a short form of "Revisions from past week that were never released", but not sure if it would be understandable without the context.

**Comment by therealjuan** [comment]
How about this?

* **Recent (xx)**  – Revisions never released from past week that share the most recent unassigned version 
* **Never released (xx)** – Any revision not released to any channel will appear here
* **All (xx)** – This include every revision (released or not) to any track

**Comment by bartaz** [comment]
> Recent (xx) – Revisions never released from past week that share the most recent unassigned version

"that share the most recent unassigned version" only applies to what is automatically selected. Opening the panel will still show all recent (from last week) revisions. So I'm not sure if we need to complicate this description by adding it.
Maybe just "Revisions from past week that were not released to any channel"?

> Never released (xx) – Any revision not released to any channel will appear here

"will appear here" seems unnecessary.

> All (xx) – This include every revision (released or not) to any track

Seems like overcomplicated description. Maybe just "All uploaded revisions"? It doesn't matter if it is released or not, so why to mention it?
