### ISSUE TITLE
Multiple screenshots uploaded in snap details pages

### ISSUE THREAD

**Issue by therealjuan** [canonical-websites/snapcraft.io#1526]
[From topic thread](https://forum.snapcraft.io/t/bug-multiple-screenshots-in-listing/9603)

There is a bug in the listings uploading the screenshots that cause screenshots to be uploaded multiple times: https://snapcraft.io/waiterio-restaurant-pos
 
![image](https://user-images.githubusercontent.com/8167677/51531963-c98c6780-1e36-11e9-90c4-c2a1689a31dd.png)

**Comment by HoLuLuLu** [comment]
I have the same issue:
[https://snapcraft.io/wps-office-multilang](https://snapcraft.io/wps-office-multilang)

**Comment by tbille** [comment]
an issue has been opened on snapstore side: https://bugs.launchpad.net/snapstore/+bug/1813614

It seems that this problem is more recurent than we think.

This needs to be fixed on storefront and store side: I opened another issue with some details that I am closing now but refencing here to keep the informations https://github.com/canonical-websites/snapcraft.io/issues/1536

**Comment by tbille** [comment]
@HoLuLuLu Thanks for notifying us, we will clean the duplicates manually in the meantime

**Comment by tbille** [comment]
from snapstore team: "fwiw, I think that if you can detect and deduplicate before hitting the API (and only push the hash once for each, without the image file), that should self-fix the situation in the next updates"
