### ISSUE TITLE
Improve snap listing page layout

### ISSUE THREAD

**Issue by therealjuan** [canonical-websites/snapcraft.io#1607]
## Main objective
To improve the current layout we display for listing metadata of owned snaps.

Some items to think about:

* Snap icon or title does not follow the style as  Snap name + Publisher
![image](https://user-images.githubusercontent.com/8167677/52954691-18bcae00-338b-11e9-9cb4-74b0cd3d2152.png)

* Video, Developer website and contact details have Label on top whilst the layout seems to be label on the left and input field . on the right with helping text underneath
![image](https://user-images.githubusercontent.com/8167677/52954750-3b4ec700-338b-11e9-826c-22c0ee262e40.png)

* Missing title for Graphs information:
![image](https://user-images.githubusercontent.com/8167677/52954782-502b5a80-338b-11e9-8310-70b17c5ab768.png)

## Design
Latest design can be found on [Zeplin](https://zpl.io/aR1XlON)

## Spec
Further details can be found on the spec [here.](https://docs.google.com/document/d/1KgprCc1WiHbtCtTQ1vSP_EIpPaC44U7UAIwTcMSAkhE/edit?usp=sharing)

**Comment by hughesjordan** [comment]
@therealjuan tidied up the layout, what do you think?

![listing layout v1](https://user-images.githubusercontent.com/17141586/53017380-ba093a00-3447-11e9-845f-bb09636849da.png)


With video preview (could perhaps make it half size so it takes up less height?):

![listing layout v1 - video preview](https://user-images.githubusercontent.com/17141586/53017412-cb524680-3447-11e9-9da1-3f623c034dda.png)

**Comment by matthewpaulthomas** [comment]
Drive-by suggestions:
- The closer this layout is to the actual listing page, the more easily developers will understand what’s appropriate for each item. For example, someone might reasonably think “I should keep the description really short, so that people don’t need to scroll far to see the video” — and they’d be wrong, because on the actual listing page the video is above the summary and description. That’s easily fixed by putting it above the summary and description here too.
- Eight separators is a bit much (the actual listing page has only two). For example, there’s no need for one between Category and Summary, or between Images and Video.
- Not sure whether it should be part of this epic, but the page could have a lot less text. For example, each image restriction is innocuous enough that it’s probably unnecessary to describe them inline until someone actually trips up on any of them. Similarly, “Please include a valid http:// or https:// link” only makes sense as an error message, so it shouldn’t be shown by default. And the “Category” caption could be much shorter (something like “Makes the snap easier to find, and improves its search ranking.”).

**Comment by hughesjordan** [comment]
Thanks for the feedback @matthewpaulthomas 

> * The closer this layout is to the actual listing page, the more easily developers will understand what’s appropriate for each item. For example, someone might reasonably think “I should keep the description really short, so that people don’t need to scroll far to see the video” — and they’d be wrong, because on the actual listing page the video is above the summary and description. That’s easily fixed by putting it above the summary and description here too.

Mostly agree, however there may be some exceptions.. e.g. when you supply a video, on the listing page it appears before any screenshots. Generally I assume most publishers will be uploading screenshots, so may be better to keep that section above the video in the edit listing page. What do you think?

> * Eight separators is a bit much (the actual listing page has only two). For example, there’s no need for one between Category and Summary, or between Images and Video.

Agreed, this was something I mentioned in separate issue regarding the media assets interface. I think grouping some of the sections could improve the layout.

> Similarly, “Please include a valid http:// or https:// link” only makes sense as an error message, so it shouldn’t be shown by default.

Considering we have inline validation it makes sense to me to retain the additional information, it is helping to prevent errors.

See a few alternative layouts [here.](https://drive.google.com/drive/folders/1-zTvKC9NWlA27kKHHLDn17cKkPxLLp84?usp=sharing) Thoughts?

**Comment by matthewpaulthomas** [comment]
> Generally I assume most publishers will be uploading screenshots, so may be better to keep that section above the video in the edit listing page. What do you think?

You’re probably right that people will provide screenshots more often than videos. But when they don’t have a video, that field is just a text entry, so it’s easy to scroll past.

> Considering we have inline validation it makes sense to me to retain the additional information, it is helping to prevent errors.

Inline validation is one way to reduce the cost of errors. Extra instructions are another way, but one that imposes its own cost of reading time. So whenever we’re using inline validation (or any other error prevention technique, e.g. an input filter), then extra instructions are _less_ worthwhile than they would be otherwise.

> See a few alternative layouts [here.](https://drive.google.com/drive/folders/1-zTvKC9NWlA27kKHHLDn17cKkPxLLp84?usp=sharing) Thoughts?

FWIW (maybe not much!), I prefer v3.png simply because it’s the most similar to the actual listing page.

**Comment by hughesjordan** [comment]
I failed to test the validation thoroughly enough - and probably a result of the text itself. I thought you would manually have to include the 'https' but the field inserts that for you! So agreed, can remove probably remove it.

**Comment by hughesjordan** [comment]
@matthewpaulthomas are you able to give this a final review please? Spec provided above which includes links to the final design.

**Comment by Lukewh** [comment]
@hughesjordan I'm not sure what value having a video inline provides? You can see the video by clicking "Preview" and having it in the form takes up quite a bit of space.

**Comment by hughesjordan** [comment]
@Lukewh Yeah, sorry I think I had discussed with Juan and agreed to drop the inline preview 🔪 it!

**Comment by hughesjordan** [comment]
@bartaz @Lukewh see some earlier designs and feedback above, again not too precious about where the description and summary fields sit. I think either way users won't struggle with the form :)
