### ISSUE TITLE
308 permanent redirect on non https links

### ISSUE THREAD

**Issue by tbille** [canonical-websites/snapcraft.io#1650]
Share a non https link the metadata shows:  

![image](https://user-images.githubusercontent.com/2707508/53757864-b00a2100-3eb4-11e9-82e8-791d43e1bcd2.png)

Test here: https://developers.facebook.com/tools/debug/sharing/?q=snapcraft.io%2F

**Comment by tbille** [comment]
This PR will fix this: https://github.com/canonical-webteam/deployment-configs/pull/203

Already applied to our nginx controller, closing this issue since not directly impact this project.

**Comment by nottrobin** [comment]
Sure this issue shouldn't have been closed until https://github.com/canonical-webteam/deployment-configs/pull/203 is merged? I'm reopening.

**Comment by nottrobin** [comment]
@tbille could you please expand the description of this issue to explain why a 308 status is a problem?

`308 Permanent Redirect` is [a standard status](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308) supported by all browsers, and so Kubernetes' use of it to signify that the domain should permanently be accessed over HTTPS is entirely valid. We need a good reason for diverging from the entirely accurate Kubernetes default.

**Comment by nottrobin** [comment]
I can see that the code [here](https://github.com/canonical-webteam/deployment-configs/pull/203/files#diff-ce83e6a40565a28c2efb012e10dfb729L3) says "301 status is not understood by social media bots", so that's presumably the better description of this issue.

My question would be, why are social media bots seeing the `http://` versions of our domains at all? Are people linking to `http://`? Are these links defined by us? If so, is it possible for us to reliably just ensure that these links are always defined as `https://` instead? If not, I can see that we might need to make this a `301`, even though that is definitely less correct than `308`. Bloody Facebook.

**Comment by nottrobin** [comment]
I did some more digging and discovered the change was originally made in https://github.com/canonical-webteam/deployment-configs/pull/42.

It was mentioned at the time that:

> As soon as it is reasonable to revert this change, we should do so.

So I still think we should re-verify that this issue exists and can't be fixed through other means.

**Comment by tbille** [comment]
As mentionned this is an issue discussed a while ago and is still the case. We had a regression when updating our k8s cluster and our configuration. Not really sure what can we do. But the problem was happening on other social networks too.

I am not sure what else can we do for now and if this is the right place to track it. Can we continue the discussion [here](https://github.com/canonical-webteam/deployment-configs/pull/42) since the change has been made manually to fix this problem and this impacts other projects too.

**Comment by nottrobin** [comment]
@tbille okay I've merged the PR. Can you please link me to something that explains the actual issue better? I accept that it was something that was necessary at some time, and if it's no longer working as needed, your simple fix probably makes sense. But there's still nothing here in any of these PRs or issues that actually describe the problem.

Are you able to provide me with any more detail?
