### ISSUE TITLE
Decide how extensively to cache requests

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#20]
As @cprov mentioned in https://github.com/canonical-websites/snapcraft-flask/pull/11#discussion_r136489529, we may want to reconsider whether we want to cache API responses in the way that we currently do. From @cprov:

> I would be more concerned about retrying failed requests than caching results in the context. Sure, the load will be not neglectable on the store services but we are in a better position to cache it properly, specially when authentication comes to play. Also, considering the possible topology of these services, both deployed in PS4.5, request round-trips won't be expensive.
OTOH, retrying 5xx request has proven to be relevant to avoid network glitches to prevent external request to be fulfilled.

I don't feel comfortable removing caching entirely however:

> I like the idea of retrying requests - that certainly makes sense. I'll also add a total timeout (2 seconds, probably), as I want to avoid this application hanging on a delayed API response.
> 
> I still have concerns about not providing some redundancy in this layer. For these public API requests, it seems to me to be perfectly valid to return cached data on error, and I think the public facing details pages should be especially resilient.
> 
> If it doesn't make sense to cache the authenticated API responses, then that's fine - I think an authenticated user would be less surprised to find that an API call was required in their requests - and it would be slightly less impactful if those pages broke.
> 
> I'd be happy to set up a different cache which honours caching headers rather than just caching for a set time (probably https://pypi.python.org/pypi/CacheControl) so that your application can choose how the response is cached if that would help. But for public pages at least, I'd still like to return cached data rather than a 500 page if we have an API error. We will still notify the user that the API response failed.

Let's continue the discussion here so it doesn't block the PR.

**Comment by cprov** [comment]
@nottrobin any solution involving per-unit caching will stop working the moment you deploy multiple  service units with behind a load balancer, the unit-caches will diverge and the benefits will be lost. If you are concerned about internal PS4.5 network reliability (there is no evidence you should be), you need a common backend-cache layer (squid, ideally) shared across all your worker-units.

As I mentioned earlier, maybe not clearly, retrying 5xx will give your app resilience against broken backend workers (store units that are temporarily malfunctioning) but does not overcome any internal network outage and realistically speaking, nothing does. In case of an internal network outage, your app wouldn't be receiving any request in the first place and in this sense preparing for it in advance without evidences of what is the actual problem falls into "premature optimization".

Instead of adding layers of complexity at this early stage, I would advise instrumenting your application for tracking problems and timing the external requests, as we do in https://grafana.ubunet.canonical.com/dashboard/db/snapstore, then based on evidence you can react with the right tool.

If you are concerned about page load timing, since the backend is your only source of data, I'd rather cache the whole external page instead of the backend request. Obviously it poses challenges for authenticated access, but they are much easier to manage at the HTTP level than inside your code.

Take my comments as suggestions and if you feel strong about local caching feel free to continue to use it. I just don't think it will ever buy you the benefits you are looking for.

**Comment by nottrobin** [comment]
Yes, I take and agree with most of those points:

- For performance, we should do whole-page caching
- Network problems within PS4.5 would affect this app equally
- Protecting against fairly unlikely hypothetical problems is premature optimization

So you're right, the one case I am really guarding against is an error in the API itself. And I feel that this is more than premature optimisation because we have multiple times had critical websites error because they relied on API calls in the back-end to other services (also within PS4.5, I believe) which went down, or started erroring, or took a long time to respond. We have this caching in API calls in our existing applications for this reason (as in from postmortem optimisations) and I have simply copied it over because I think it applied just as much to this app.

I am not questioning the quality of the Snapcraft API, I'm just saying I think it is wise to be resilient against it experiencing problems.

**Comment by bartaz** [comment]
@nottrobin Is this discussion still open or can it be closed?

**Comment by nottrobin** [comment]
I think it can be closed for now.
