### ISSUE TITLE
Install button visible on Android

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#207]
Snap details page shows the install button when visited on Android phone (Android 6, Chrome) while it is not possible to use the button (clicking doesn't do anything).

![screenshot_20171221-120210](https://user-images.githubusercontent.com/83575/34253324-5c02dc62-e647-11e7-8f44-fe9db185d755.png)

**Comment by bartaz** [comment]
How to best approach it?

Currently we just check if "Linux" is in the user agent.
We could keep this, but remove some 'false positives' such as Android.

Or we could define the list of systems we know Install should work and limit showing install button just for them? Currently it will be Ubuntu, but can we add anything more to the list reliably?

As far as I know currently it's impossible to tell from inside the browser that `snap://` URL will be handled properly (without some not very reliable hacks).

**Comment by caldav** [comment]
What about the elementaryOS approach? For example: https://appcenter.elementary.io/com.github.lainsce.quilter

**Comment by matthewpaulthomas** [comment]
The appcenter.elementary.io approach is exactly to include Linux and then exclude Android:
```js
if (isLinux && isAndroid === false) {
```
[Spec updated](https://docs.google.com/document/d/1p0FOzR9boI35RmsCKPOn0HNRY_kbFAS-zXqpPLh2Ot4/edit#heading=h.gbs1st667eb3). (This part of the design is currently subject to change in [snapcraft-design#108](https://github.com/CanonicalLtd/snapcraft-design/issues/108).)

**Comment by caldav** [comment]
Of course. I meant the fact that with this intermediary page, an "Install" button linking to https://appcenter.elementary.io/com.github.lainsce.quilter, has an effect regardless of your platform. If you are on a supported platform, when reaching this page, you will see xdg-open opening whatever it's trying to open. If not, you will see steps to achieve what you wanted when you clicked. Instead of a button that you may or may not be able to click.

**Comment by matthewpaulthomas** [comment]
Ah, that’s a broader question than this simply-fixable Android issue. A store URL redirector — like appcenter.elementary.io, itunes.com, or apt.ubuntu.com — exists largely [to cater for CMSes outside your control](https://wiki.ubuntu.com/AptUrlRedirector#Rationale), whereas our own Web directory can happily link to `snap:` URLs directly. Now, we could still make our “Install” buttons go to a separate page like that. But if it’s technically possible, I think any failure UI would be less jarring displayed on the directory page — even in an overlay on that page — rather than on a separate page.
