### ISSUE TITLE
Incorrect testimonial design on the homepage

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-websites/snapcraft.io#275]
The What people are saying... section is using the wrong testimonial design. The correct one can be found on [build.snapcraft](https://build.snapcraft.io/)

![image](https://user-images.githubusercontent.com/9105999/35619518-38954b1c-0676-11e8-89b5-b242f51fe758.png)

**Comment by lyubomir-popov** [comment]
@bartaz could we retain the headings and conform to the design on build.snapcraft.io? The format is not ideal due to the length of the copy, but further explorations were phased out last time we discussed this.

**Comment by lyubomir-popov** [comment]
@kwm14 @spencerbygraves Update on this, partly based on our discussion in the design meeting yesterday.

The design referenced above works well with the amount of copy used for the mockup, but we're dealing with a lot more copy.

There's a separate request to make logos n testimonials more prominent, and there's also research showing that putting a face to a testimonial makes them more convincing [needs a reference to research, will try and find one].

That said, obtaining a photo is not always possible. So the suggetstion bellow tries to make the best out of those requirements and constraints.

• Does away with the exagerated orange quotation marks, as that requires space we could use to better fit copy in tight 3 column layouts.

• Increases prominence of logo, by placing it next to the excerpt rather than next to text. Two things to note: 
 – in this position longer logos like heroku fit well as there's no width constraint (only a height constraint of 24px).
– keeping the rest of this line clear of person / company name allows those to not be arbitrarily offset, which happens in the original designs by Joanna.

• Having cleared the space next to the name, we can now use it to fit optional images in a circle there. I think this works even when some of the quotes have an image, which means we don't have to not use one photos when only one of the people consented to providing one.


Proposed design:

![tewstimonials section proposal](https://user-images.githubusercontent.com/2741678/39518800-446a2200-4dfc-11e8-834c-50983148faa3.png)

For reference, the existing implementation:

![image](https://user-images.githubusercontent.com/2741678/39518747-1f2e3396-4dfc-11e8-908a-14e96ffbeedc.png)

**Comment by lyubomir-popov** [comment]
@kwm14 @spencerbygraves  talked separately with both of you, but just to confirm here, we're fine with this being implemented for snapcraft and proposed to vanilla, and then we'll combine this with https://github.com/vanilla-framework/vanilla-framework/issues/1779 and have two versions - 
• a hero 12 column testimonial
• a compact 3-column testimonial

**Comment by spencerbygraves** [comment]
@lyubomir-popov Yes, I think that sounds fine. @kwm14 are you happy with that?

**Comment by kwm14** [comment]
@spencerbygraves yes I'm happy with the new proposal, it's evolved slightly from Joana's original design but looks good 👍 

@lyubomir-popov mentioned that @bartaz will be building this so we can propose it to Vanilla and I'll create a design spec after to document new component 😄

**Comment by lyubomir-popov** [comment]
@bartaz logos here:
https://assets.ubuntu.com/v1/814e1a01-heroku-logotype-horizontal-purple.svg
https://assets.ubuntu.com/v1/477b9b52-microsoft-logo.svg
https://assets.ubuntu.com/v1/7ba8b190-jetbrains.svg

**Comment by Lukewh** [comment]
@lyubomir-popov one issue, with the JetBrains logo:
![Screenshot-2018-5-15 Snapcraft - Snaps are universal Linux packages.png](https://images.zenhubusercontent.com/59316f3551aa2c3057803f4b/70932c98-dee3-4279-920c-f389ed116ffa)

**Comment by lyubomir-popov** [comment]
@Lukewh I'll need to resize the logos with the logo template. Assigning to myself, will try to do it before the end of the week.

**Comment by lyubomir-popov** [comment]
@Lukewh could you please make the size of the logo container have a height of 3rem, and once the images are properly sized, it will fit nicely.

**Comment by Lukewh** [comment]
@lyubomir-popov so should the icons have a height of 3rem or:

> – in this position longer logos like heroku fit well as there's no width constraint (only a height constraint of 24px).

24px?

**Comment by lyubomir-popov** [comment]
Please use 3rem. I forgot the resizing bit when we mentioned it in the standup, sorry. I'll resize them on Monday if that's ok.

**Comment by Lukewh** [comment]
@lyubomir-popov no worries. I've updated https://github.com/canonical-websites/snapcraft.io/pull/657 and http://snapcraft.io-pr-657.run.demo.haus/ with the 3rem height.
