### ISSUE TITLE
Canonical websites stylised as external

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#288]
<img width="621" alt="screen shot 2018-02-07 at 16 11 37" src="https://user-images.githubusercontent.com/1523179/35927077-aec63ade-0c21-11e8-80f4-01c639c599fa.png">

I may misunderstand the intent of the external link hints, but I take them to mean "we have no control over what happens beyond this link, so tread carefully." All the links in the header on snapcraft.io, build.snapcraft.io, and docs.snapcraft.io point to Canonical-run websites. However the ones at snapcraft.io subdomains or ubuntu.com are stylised as external.

**Comment by matthewpaulthomas** [comment]
Coincidentally we discussed this issue in the squad yesterday.

A problem with using an external-link icon to mean “we have no control over what happens beyond this link” is that hardly anyone would know what “we” means. Even when I asked people who Canonical had invited to the Snapcraft Summit, “Who would you say is responsible for this site?”, hardly anyone suggested “Canonical”.

We use the external-link icon instead to mean “this link goes to a different site”. People can have varying opinions about exactly what a “site” is. But users are likely to interpret two sets of pages as being the same site if their designers have treated them as such. This manifests as things like:
- the logo has the same appearance and position
- the logo links to the same page
- the top-level navigation links are the same
- the global search function, if any, searches the same set of pages
- if you’re signed in to one, you’re signed in to the other.

All else being equal, we’re better off with snap publishers having to learn fewer sites, and we look more coherent if top-level navigation isn’t pointing to external sites. For example, right now many people would interpret snapcraft.io and docs.snapcraft.io as separate sites, because while the header elements are the same, they have very different font size and position. This will be fixed in [snapcraft-design#277](https://github.com/CanonicalLtd/snapcraft-design/issues/277), at which point we can mark “Docs” as no longer being an external site. If forum.snapcraft.io manages to achieve the same (a big challenge, apparently), we can do the same for “Forum”.

As for tutorials.ubuntu.com, that will remain an Ubuntu-branded site with Ubuntu navigation, and therefore a different “site” to any reasonable observer. Yesterday we discussed three approaches to solving that:
- Linking instead to a snapcraft.io “Tutorials” page that indexes tutorials.ubuntu.com’s Snapcraft category (though I guess every tutorial link on that index would then be external).
- Removing the item altogether, replaced by a “Tutorials” link on docs.snapcraft.io/.
- Removing the item altogether, and instead (as I mailed you on Nov 27th) linking only to individual tutorials from the relevant docs.snapcraft.io page, on the grounds that nobody will guess that it might be a good idea to browse a Tutorials index just in case we have a tutorial on a particular topic.
