### ISSUE TITLE
503s on https://snapcraft.io/skype

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#292]
Hi,

There was a period on Feb 7th where https://snapcraft.io/skype was intermittently 503ing. Can you please dig into the logs to get a sense of how frequently this is happening and potentially why it is occurring?

**Comment by shivjoshi1996** [comment]
We are going to wait for analytics before investigating this

**Comment by cprov** [comment]
@nottrobin We've noticed that all the traffic to {api, dashboard}.snapcraft.io is going through `squid.internal`, which is not meant to handle the current volume and nature of access. It might as well be some of the unresolved corners of CDK within our datacenter, so I suggest we discuss more viable alternatives with IS for routing this traffic more efficiently. `squid.internal` is not helping and hammering it is probably also affecting other services, like build.s.io -> GH traffic. 

The store was indeed returning 503 on `searches` in specific moments when snapd was effectively DDoS the infrastructure due to a bug. It's gone now, but might happen again and we will continue to sacrifice `searches` for sustaining `refreshes`. The purpose of the custom caching layer (temporarily  dropped due to a security bug) was to provide known-good cached information for a while to overcome sporadic 5xx response (blips), but it never worked as intended. We should revisit that implementation for increasing robustness of the home (featured snaps) and the public snap pages.

**Comment by nottrobin** [comment]
> @cprov We've noticed that all the traffic to {api, dashboard}.snapcraft.io is going through `squid.internal`

Interesting. As far as I'm aware, all traffic for snapcraft.io *does not* go through `squid.internal`. Outbound traffic from some of our other sites does, but not snapcraft.io, currently. If you know differently then this is unintended - could you please let us know how you discovered this and we'll look into it?

Yes we will be working on making all pages on snapcraft.io more resilient to the APIs being down, so they show more elegant errors to the user. Although we have always been intending to make sure snapcraft.io is resilient in this way, this hasn't been prioritised partly [following your suggestion](https://github.com/canonical-websites/snapcraft.io/issues/20#issuecomment-326648534).

**Comment by cprov** [comment]
@nottrobin Sorry, no where in the original comment I've suggested that you should 500 on your app if any of the many API calls in your backend ends up failing with 5xx, even after retrying (suggestion I stand by). Rendering `Sorry, information temporarily unavailable.` in a section that depends on unavailable remote information and logging an error for future reference is pretty basic practice and much safer than relying on the last successful request to be cached indefinitely (and magically) and pretend everything is fine (remember cache-invalidation-is-hard).

In fact, everything that I've pointed as a risk back then was ignored and unfortunately resulted in the breach from last week that we all have to deal now (untested and buggy caching layer being misused for authenticated request).  None of the recommendations to instrument the application with metrics and logging alerts were considered and we continued to make decisions that were not based in any evidence but 'I think it would work better like this'.

For the sake of having a more productive conversation, please let's stop pretending you are doing what I have suggested, because you are definitely not!

Regarding the issues with squid.internal,  kubernetes-worker spec `lp:canonical-mojo-specs is/kubernetes/deploy` sets `http_proxy:  http://squid.internal:3128` so it's very likely that is what the running applications see, even if they do not set anything explicitly.  I suggest you file an RT to get this aspect investigated and a more viable solution implemented. There is no need to stress squid.internal with requests to api.snapcraft.io, it's not buying your app anything and unnecessarily competing with other applications consuming external resources.

**Comment by nottrobin** [comment]
> Regarding the issues with squid.internal, kubernetes-worker spec lp:canonical-mojo-specs is/kubernetes/deploy sets http_proxy: http://squid.internal:3128 so it's very likely that is what the running applications see, even if they do not set anything explicitly.

Interesting point - I've filed RT #109532 to confirm that. I don't believe it can be the case because we've had to explicitly add `HTTP_PROXY=squid.internal:3128` to certain k8s services to fix connection issues to external services, but it's certainly best to check.

> In fact, everything that I've pointed as a risk back then was ignored and unfortunately resulted in the breach from last week that we all have to deal now (untested and buggy caching layer being misused for authenticated request). None of the recommendations to instrument the application with metrics and logging alerts were considered and we continued to make decisions that were not based in any evidence but 'I think it would work better like this'.

Much of what you've suggested is definitely a good idea - we are working towards implementation many of your suggestions. To say your suggestions are "ignored" is a little unfair. We appreciate the tests you wrote, and we are working to [add sentry.io](https://github.com/canonical-websites/snapcraft.io/issues/336) and [prometheus metrics](https://github.com/canonical-websites/snapcraft.io/issues/340).

My main point, though, is that whether we display a friendly "Sorry, information temporarily unavailable." message, or a blunt server error page, the entirety of the information at  https://snapcraft.io/skype will be unavailable if the API is unavailable. The only way to be protected against that is caching. I completely agree that the friendly message is preferable, and we will work towards implementing it.

**Comment by nottrobin** [comment]
Both we and IS have made a number of reliability improvements to the snapcraft.io hosting environment, and more are coming down the line.

We haven't seen or heard of these 503s in a while, so I'm going to close this. We can open another issue for future errors.
