### ISSUE TITLE
503 on market page for non-existent or no-perms-to snap

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#305]
<img width="1005" alt="screen shot 2018-02-15 at 10 00 03" src="https://user-images.githubusercontent.com/1523179/36250938-4c7066f4-1237-11e8-9804-4bfd32ba7330.png">

To reproduce:
- Edit the URL to view the market page to use a random string of characters or a snap you do not have permissions to

What should happen:
- A friendly message explaining that snap cannot be found

**Comment by matthewpaulthomas** [comment]
There are three separate cases here:
1. “random string of characters”: should be the standard 404 page, obvs.
2. “you do not have permissions to” because you’re not signed in: should redirect to sign in, then bring you back. (And so should any other URL under `/account`.)
3. “you do not have permissions to” because you’re signed in as someone who isn’t a collaborator: should be a 401 Not Authorized. (Later we can make that page helpful by suggesting that you sign in as someone else, or that you get yourself added as a collaborator.)

I’m not sure about the last case, because someone who was signed in could interpret the fact that they got a 401 rather than a 404 from `snapcraft.io/account/snaps/extremelypopularapp` as evidence that extremelypopularapp’s vendor was working on a snap — even if it was unreleased, marked private, or J. Random Snapcrafter. What do you think @evandandrea?

**Comment by evandandrea** [comment]
I agree. We do not want to leak knowledge of a snap the user cannot install.

**Comment by Lukewh** [comment]
@evandandrea @matthewpaulthomas anything that is deemed as 'behind auth' should redirect to login, everything else should be a 404. Unless it's a genuine server error, then a 5** is appropriate.

But yeah, the initial issue seems like it's a 503 masking a simple 404.
