### ISSUE TITLE
Screenshots - No help text for screenshot requirements

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/snapcraft.io#413]
No requirements explained:
- on initial view
- on initial upload
- on applying changes

It would be more helpful if the screenshot requirements were explained up front, or the files were validated on initial upload to 'staging' and more helpful error text given _E.G. The image you selected must be in PNG or JPEG format_
# 
Triaged from #365

**Comment by Greggless** [comment]
- Closely related to: https://github.com/CanonicalLtd/snapcraft-design/issues/180
- Relevant comment: [Hiya!](https://github.com/CanonicalLtd/snapcraft-design/issues/180#issuecomment-351763568)
- How this is executed will depend on how @matthewpaulthomas solves the [related issue^^](https://github.com/CanonicalLtd/snapcraft-design/issues/180)
- Partially solves: #412 

## On initial view
### What it looks like now:

![image](https://user-images.githubusercontent.com/23459065/37958167-a81f1240-31a7-11e8-8a58-e2672630b152.png)

### What it could look like:
![image](https://user-images.githubusercontent.com/23459065/37958976-ce80ef24-31a9-11e8-9e33-5386721bebda.png)

## On initial upload
(No 'initial' upload for first implementation of screenshots)
- But if we can, can we omit .svg and other incompatible file types from being selected in the file picker? @bartaz 

## On applying changes
![image](https://user-images.githubusercontent.com/23459065/37959308-c04e247a-31aa-11e8-8387-524514188f5e.png)

**Comment by matthewpaulthomas** [comment]
> But if we can, can we omit .svg and other incompatible file types from being selected in the file picker? 

We can `<input type="file" accept="image/jpeg,image/png"`…`>`. However:
- I haven’t found a straight answer to whether/which browsers currently use this to prevent selection of unwanted types.
- Even if all browsers do, you always need server validation as well, because clients can lie.

If most/all browsers currently do prevent unwanted types, though, that could mean we don’t need extra text “Format: .PNGs and .JPEG” ahead of time. We can have just error feedback for that requirement.

> ## On applying changes
>…
> ### What it could look like:

Ah, that’s [the same approach I took](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#heading=h.leby91ua8xcu), just with different text. I think the word “uploaded” would be ambiguous here. I also used a single error message for the dimensions, since a screenshot might be both too narrow and too tall, or both too wide and too short.
