### ISSUE TITLE
[Pattern] Update key-value table

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#44]
Create a modifier pattern for a key-value table, as per designs.

**Comment by matthewpaulthomas** [comment]
Specifically:
- Make the key (header) cells use grey, while the value cells use black. (It’s more obvious that the first column consists of header cells when the table has only two columns.)
- Right-align the key cells.
- Remove the horizontal lines between rows. (They exist because of the potential large gaps between columns; right-aligning the headers solves the same problem with less noise.)

**Comment by bartaz** [comment]
@spencerbygraves @matthewpaulthomas 

As per Spencer's designs table has dotted border between the rows:

<img width="1034" alt="screen shot 2017-09-15 at 13 34 32" src="https://user-images.githubusercontent.com/83575/30480770-c0556afe-9a1b-11e7-8e48-aa67741c8eb4.png">

But Matthew suggested above to drop the lines as unnecessary noise (when keys are right aligned):

<img width="1033" alt="screen shot 2017-09-15 at 13 34 56" src="https://user-images.githubusercontent.com/83575/30480846-2a32dc2c-9a1c-11e7-8a71-7ca51ec161ba.png">

@spencerbygraves @matthewpaulthomas Which version should be implemented and proposed to Vanilla?

**Comment by carlaberkers** [comment]
done. closing
