### ISSUE TITLE
Design fallback "install" text for non-Linux visitors

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#45]

**Comment by matthewpaulthomas** [comment]
For now, I suggest that the fallback text be:

> This software, and hundreds of others, are available on snap-powered systems like [Ubuntu](https://www.ubuntu.com/download).

@evandandrea Can we set a reminder to update this text when either:
- there are multiple released OSes with both snapd and `snap:` handling by default (when we should set up some kind of [explanatory page](https://whatbrowser.org/))
- the number of stable snaps passes 2000 (change “hundreds” to “thousands”).

**Comment by evandandrea** [comment]
@matthewpaulthomas why stable specifically?

**Comment by nottrobin** [comment]
I also think it's fair to say software "is available" on snap before it's necessarily stable.

Also, can you not say that 1.2 thousand is a multiple of a thousand, and therefore thousands?

**Comment by matthewpaulthomas** [comment]
Fortunately those points are moot, because [I changed the wording](https://github.com/canonical-websites/snapcraft-flask/pull/57#issuecomment-331157376) to just “You can install this software on a snap-powered system like Ubuntu.”

But briefly, because it might reveal an inconsistency in the snap page implementation: [`snap find` returns only snaps with a stable non-branch release](https://snapcraft.io/docs/reference/channels#discoverability-of-snaps), and therefore, I’ve been designing on the assumption that snaps will have an end-user page only if they have a stable non-branch release. (For example, in the “Release” admin view, I’ve drawn [“View in the Snap Directory” buttons only next to stable releases](https://github.com/canonicalltd/snapcraft-design/issues/56#issuecomment-325942820).) And it would have been odd for an end-user page to count snaps that don’t themselves have end-user pages.

So far this hasn’t been spelled out anywhere, because so far there hasn’t been a design spec for the page. Probably there should be.

**Comment by matthewpaulthomas** [comment]
> So far this hasn’t been spelled out anywhere, because so far there hasn’t been a design spec for the page. Probably there should be.

Added this text to [a skeleton design spec](https://docs.google.com/document/d/1p0FOzR9boI35RmsCKPOn0HNRY_kbFAS-zXqpPLh2Ot4/edit#heading=h.pdu64zjt40nr). 💀🎃

Text reviewed by @carlaberkers today.
