### ISSUE TITLE
Screenshots can be scrolled far more than necessary

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#456]
1\. Go to [the Toto snap page](https://snapcraft.io/toto).
2\. If necessary, resize your window so that the row of screenshots scrolls.
![snapcraft io-screenshots](https://user-images.githubusercontent.com/19801137/37954541-05510d24-319e-11e8-8ffc-7e2831b20f74.png)
3\. Click the right scroll button until you get to the last screenshot.
4\. Click the button again.

What happens: You can keep scrolling until the last screenshot is the _only_ screenshot visible.
![snapcraft io-screenshots-scroll](https://user-images.githubusercontent.com/19801137/37954545-08baa998-319e-11e8-8803-2eb7f3c3b702.png)

What should happen: You can keep scrolling until the last screenshot is completely visible, and no further.

**Comment by bartaz** [comment]
Agreed, initially I wanted to implement it this way, but it turned out to require a lot of calculations and has some edge cases - especially that width of visible screenshots area is responsive and screenshots themselves may have variable widths.

I preferred to implement simpler solution first and hopefully enhance it later.

**Comment by Lukewh** [comment]
Using swiper this seems to be resolved.
