### ISSUE TITLE
Text in Snap Store button isn’t accurate

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#557]
The badge we provide for snap publishers currently says “Download from the Snap store”.

This has two issues:
- When you get the snap, you’ll end up either using a command line we provide, or (later) installing it from a local storefront. You aren’t “downloading” it in the way that people are used to Web pages talking about.
- It’s “Snap Store”, not “Snap store” (references [1](https://snapcraft.io/), [2](https://docs.snapcraft.io/build-snaps/publish)).

So: “Get it from the Snap Store”

[First issue originally pointed out by @nottrobin during end-of-iteration demos.]

**Comment by nottrobin** [comment]
I think "Install it from the Snap Store" would also be fine. I know (as @cassiocassio pointed out) you might not end up installing it, but I think it's fine to imply that that's the main reason you should go to the store - a kind of hint that we want to you install it.

But I'm not at all precious. Either wording is fine with me, as long as it's not "Download".

**Comment by Greggless** [comment]
@lyubomir-popov @kwm14 Could you update and re-upload the assets, pretty please?

**Comment by matthewpaulthomas** [comment]
It’s probably a good idea to fix [snapcraft-design#286](https://github.com/CanonicalLtd/snapcraft-design/issues/286) at the same time as this bug.

**Comment by matthewpaulthomas** [comment]
@lyubomir-popov No, neither Robin nor I particularly mind which of those two. If in doubt, flip a coin. :-)

**Comment by lyubomir-popov** [comment]
@matthewpaulthomas updated the english ones, waiting for the translations to be updated to produce the rest:

https://assets.ubuntu.com/v1/44a9abad-snap-store-badge-dark-en.svg
https://assets.ubuntu.com/v1/24140745-snap-store-badge-light-en.svg

**Comment by lyubomir-popov** [comment]
Ok. I will use "Get it". If anyone disagrees, please follow up before this has been localised.

https://assets.ubuntu.com/v1/44a9abad-snap-store-badge-dark-en.svg
https://assets.ubuntu.com/v1/24140745-snap-store-badge-light-en.svg

**Comment by shivjoshi1996** [comment]
@lyubomir-popov @matthewpaulthomas @nottrobin After speaking to a couple of guys in the company who speak German, they told me that translating "Get it from" in a formal way was a hard thing to do...and "Install from" would be better, so I think we should go with "Install from the Snap Store".

**Comment by nottrobin** [comment]
@shivjoshi1996 that seems like a terrible reason to choose wording in English. If "Get it from..." translates badly, then the translation should simply say the German equivalent of "Install from...". That should have no impact on whether "Get it from" sounds better in English.

**Comment by shivjoshi1996** [comment]
@nottrobin I was thinking of it more from a consistency POV. Since it was a toss-up between "Install" and "Get" anyway, why would we not try and be consistent? 

@matthewpaulthomas @lyubomir-popov What do you think?

**Comment by nottrobin** [comment]
@shivjoshi1996 I'm not actually defending "Get it from" at all, I have no horse in this race. But the German translation of anything should never be used as even the smallest argument for choosing English wording. How does it translate in Arabic or Greek or Tamil? It's a horrible precedent to set as an argument.

**Comment by shivjoshi1996** [comment]
@nottrobin I get your point, but I think this would be a bigger problem if we had a preference between the word "get" and "install". If we have no preference, then why are we fixed on an option that was chosen by @lyubomir-popov at random? 

 I also spoke to @therealjuan about this and he said that "get" also doesn't sound all that great when translated into Spanish. I'm not using this to set a precedent, I'm just saying we might as well be consistent between languages since we aren't fixed to "install" or "get" in English.

Either way, I'm not a UX'er. Whatever @matthewpaulthomas & @therealjuan chooses, I'll get the translations for.

**Comment by matthewpaulthomas** [comment]
To be fair, this is not the first time I’ve seen non-translators (or beginning software translators) make this mistake. They’re thinking only of their particular target language — forgetting that for just about any source string, there’d be _some_ language it’s hard to translate into!

In this context, “Get it from the Snap Store” and “Install it from the Snap Store” mean exactly the same thing. One happens to be slightly friendlier and shorter in English. But if someone thinks one is easy to translate while the other is difficult, they’re taking the text wayyyy too literally.

I don’t think consistency between languages matters a jot here. If we were following the standard localization method and I was writing the [translator comments](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html), I’d write:
````po
# This refers to the process of downloading and installing the software for your device.
# If possible, translate so that there are no words after “Snap Store”.
# If there are still several ways to do it, prefer friendlier rather than more formal.
````

**Comment by therealjuan** [comment]
I would probably go with "Install ..." as it translates better in 2 out of 3 languages, sounds perfect in the third one and actually when you are going to install the Snap you do `snap install` no `snap get`

**Comment by nottrobin** [comment]
@therealjuan and @shivjoshi1996 I completely agree with @matthewpaulthomas here, regardless of how little reason we have for picking "Get", it is never worth making an argument because of how it translates anywhere. As Matthew said, it's a pretty crap translator who can't translate "Get it from the snap store" into "Installiere es von snap store" or whatever (I'm not a German speaker).

I also think "Get" is slightly shorter and friendlier sounding and slightly helps with the fact that actually you might not want to "install" the software per se., but the wider point is that it matter not one jot how it translates into any language, and we really should never be using it as a reason.

"sounding friendlier" is a good example of exactly why you shoudn't let your wording preferences  be polluted by worrying about translation. There are many many times when it's difficult to explain why one wording choice sounds better than another, but it just does, to native speakers, and it will to our users too.

**Comment by matthewpaulthomas** [comment]
Besides what Robin said, I just looked at this much-vaunted [German translation](https://github.com/CanonicalLtd/snapcraft-design/issues/291#issuecomment-386300474), and immediately noticed a big problem:
> Aus dem Snap Store installieren

If the problem isn’t obvious, recall my hypothetical translator advice:
```po
# If possible, translate such that “Snap Store” is at the end of the string.
```
That’s an unusual thing to ask for. Why did I write it? Because if you put “Snap Store” in the middle of the string, as in the German above, you end up with something like this:

![snap store button de](https://user-images.githubusercontent.com/19801137/39629969-ce516a78-4fa5-11e8-83eb-6dd71945b5f0.png)

Either the padding would be awful, or all the text would have to get smaller to make room for three lines, making the German button harder to read (and, if it matters to you, inconsistent with other languages). For a button like this, wanting the English text to be text that you can translate word-for-word is an _even worse_ idea than it is normally.

[Google Play’s button](https://play.google.com/intl/en_us/badges/#badge-generator) in English is “GET IT ON Google Play”. But in German it’s “JETZT BEI Google Play”, which means “NOW AT Google Play”. That’s quite a different meaning, but it serves the same purpose, and preserves the two-line layout. Again, exact translation is not the goal.

**Comment by lyubomir-popov** [comment]
I downloaded the full pack of localised apple store badges and this is what the german one says:

<img width="482" alt="screen shot 2018-05-04 at 15 02 00" src="https://user-images.githubusercontent.com/2741678/39632192-56721d7a-4fac-11e8-9d61-f135f97d512b.png">
