### ISSUE TITLE
“My snaps” links to a mostly-useless UI

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/snapcraft.io#595]
1\. Go to [snapcraft.io](https://snapcraft.io/).
2\. Click “My snaps”, and sign in if necessary.

What happens: You end up at [snapcraft.io/account/snaps](https://snapcraft.io/account/snaps), which is roughly 10% done, and therefore mostly not useful to publishers. There’s no way to see which channels any of your snaps is released in, no way to see the revision history, no way to see any information about a release (architecture, core version, confinement, etc), no way to make a new release, no way to add or remove a collaborator, no way to add a video link, no way to set a distribution whitelist/blacklist, no way to make the snap private or public, etc.

What should happen: You end up at [dashboard.snapcraft.io/snaps/](https://dashboard.snapcraft.io/snaps/), where you can do all of those things.

It doesn’t matter that we plan to reimplement all of those things in the future: the people following this link each day over the next few months can’t use something that doesn’t exist yet. And it doesn’t matter that the new pages link back to Dashboard: that’s a good idea regardless of which UI is more functional, but users still shouldn’t be taken to a mostly-useless UI by default.

**Comment by bartaz** [comment]
@Greggless @matthewpaulthomas 
I guess this issue is better place for 'My snap' linking discussion.

If current solution ('My snaps' linking to new UI + banner linking to dashboard) is not enough and users should be still linked to dashboard with main navigation link, we need another link to new 'My snaps'.
Two 'My snaps' links in main nav (even if named differently) will be very confusing.
Maybe we could place a new link in user dropdown.

So in such case:
- 'My snaps' in main nav will remain external link to dashboard.
- after user signs in on 'snapcraft.io' they are redirected to new snaps page
- when they open the user dropdown they will have: 'My snaps' (likely named differently?), Account details and Sign out

Still, we need to have a better names to distinguish between old 'My snaps' (dashboard) and new 'My snaps'.

<img width="1047" alt="screen shot 2018-04-30 at 07 19 06" src="https://user-images.githubusercontent.com/83575/39420547-5040f8a8-4c65-11e8-9201-55b0a4e4df3f.png">

**Comment by matthewpaulthomas** [comment]
For all the excellent work everyone’s done on the snapcraft.io/account pages, they’re still much, much less functional than Dashboard. That’s no-one’s fault, it’s just that we have a lot more to design and implement over the next several months. And I don’t think it’s an exaggeration that directing people to a much-less-useful UI by default, for that period, would make snaps less successful than they would have been otherwise.

So, what was the motivation for the header to link to snapcraft.io/account instead? Was it the navigation issues described by @bartaz? Or was it just a desire to tick off a box on a roadmap labelled “Go live with new publisher pages”? 😉

If it’s the navigation issues: @bartaz is right about needing better names. I was wrong to suggest that we use “My snaps” to refer to both UIs, because I didn’t think through the breadcrumb problem. Maybe we could label snapcraft.io/account as “My snaps”, and dashboard.snapcraft.io as “Dashboard”. That way, the snapcraft.io/account/snaps/`*`/`*` pages can continue using “My snaps” as their breadcrumb link, which will be obviously distinct from the “Dashboard” link in the header. Does that seem reasonable?

(On the other hand, if it’s the roadmap thing, then it’s an unfortunate example of that [Goodhart’s Law](https://en.wikipedia.org/wiki/Goodhart%27s_law) I keep yammering on about.)

**Comment by Greggless** [comment]
I'm with MPT on this. Whilst Dashboard has the majority of the functionality it'd be frustrating for using to continually be directed to `/account/snaps` where it holds a limited set of features. It would also be annoying to have to _remember_ where features lived:
> "oh... collaboration is on the old version, let me navigate back there `*click*` `*click*` `*click*`"

I specc'd that until there was a major release of features, we should point to Dashboard. This also means that we can have a 'hard' launch, where we can shout and publicise the fact we have a shiny new UI that does 90% of the things that publishers do most often. 

I don't think this is a case of Goodhart's law, as we've launched the pages and they are live, so that's whatever tickbox ticked. It's a case that we shouldn't be too proud at what we've done, because end user's aren't going to say:
> 'Oh well done Canonical, you've got a few good pages! Good effort! I don't mind continually flipping websites to find what I need..."

(For the record, I'm very proud with what we've achieved and it's amazing to see things come to life! But there's a long way to go before we have a full product)

**Comment by matthewpaulthomas** [comment]
Summary from meeting this morning:
- snapcraft.io/account being much less useful than Dashboard is less of an issue for people who haven’t used Dashboard before.
- A bigger problem is that, with the “Store” pages becoming more popular, end users have been creating Dashboard accounts in the expectation that “My snaps” will show what snaps they have installed. ([I predicted last August](https://docs.google.com/document/d/1FkVSByHbSQljDXLw215GSWt21GFUip9SxO-NeG9Vrmk/edit#heading=h.anri58a7vnzs) that “Combining developer and end-user sites would make the top-level navigation confusing for end users”.)
- To mitigate this, we should investigate replacing the “My snaps” link with a landing page that describes the publishing process and the various UIs. I’m tracking that work as [snapcraft-design#438](https://github.com/CanonicalLtd/snapcraft-design/issues/438).

**Comment by matthewpaulthomas** [comment]
Ok, that [Publish landing page design](https://github.com/CanonicalLtd/snapcraft-design/issues/438) is now ready for discussion with stakeholders. So how about this for a mini-roadmap:

1. Short term (<1 week): Change the “My snaps” link to “Dashboard”. This will (a) fix the problem of end users thinking “My snaps” is installed snaps, and (b) fix the usefulness problem.

2. Medium term (2~4 weeks): Agree and implement the Publish landing page, and link to that instead. This will fix the problem of not explaining the scope of the four current UIs and where they overlap.

3. Long term (~12 months): Integrate and retire Dashboard and build.snapcraft.io, so that we have only one Web UI to rule them all. Then we can refer to the command line within that Web UI, and we won’t need a separate landing page any more.

**Comment by therealjuan** [comment]
Thanks for putting the proposed roadmap but there are a few additional things to consider here:

* General consensus among the wider team that (a) My Snaps is a confusing term and (b) the new account pages is what we should be pushing for and (c) provide even more publisher tooling to publishers We heard this from many different team members among the Store, Advocacy, Snapcraft... in roadmap discussions as well as been mentioned in 2 or 3 review meetings

* Maintaining the old "dashboard" is a hard case to support when data is not showing that the assumption that users will miss these features is a fair assumption to make.

* Using the term "Dashboard" is confusing from a product standpoint as it implies that holds more metrics and better overall summary on Snap performance rather than Snap management features

* Explicit feedback from MS praising the look and feel of the new publisher pages making look Snapcraft as the best Store out there

* This is more of a personal assumption of mine but releasing something new and rollback to the preivous state can lead publishers to perceive Snapcraft being unreliable

* We have explicitily commited to migrate the new account pages and if we don't push from all angles, it can be difficult further down the line to push other teams to provide the support we need to roll out the "Dashboard" features

So blending all these items what it makes sense at this point in time is to:

1. Remove 'My Snaps' from the top navigation
2. Include 'My published Snaps' in the account navigation as well as "Build with GitHub"
3. Start working on integrating old new features into the account pages

There is a good buddhist sentence that I believe is applicable to this issue: "Don't let the perfect be the enemy of the good"

**Comment by carlaberkers** [comment]
Completely agreed Juan. Let's move forward with Juan's proposal as it does justice to the broader snap squad, engineering teams and stakeholders requirements. It's time to let this go and look focus on migrating the other functionality so we can retire dashboard for publishers soon.

**Comment by matthewpaulthomas** [comment]
I agree that “My snaps” and “Dashboard” are both confusing terms, that we shouldn’t maintain Dashboard longer than necessary, that the new pages look better, and that we’re committed to migrating to them. Fortunately, none of those are relevant to this issue: which UI we link to from the header in May 2018 has no effect on how long we’ll maintain Dashboard, our intention to replace it, our speed in replacing it, or how good the replacement will look. The main effect it _does_ have is on how quickly publishers can perform various tasks in May 2018.

Irrelevancies aside, removing the link altogether would indeed fix this issue: we would no longer be linking from the header to a mostly-useless UI. It’s not the fix I had in mind, obviously, 😉 but an example of the usability penalty of trying to cater for end users and publishers on the same Web site.

**Comment by matthewpaulthomas** [comment]
I’ve implemented @therealjuan’s proposal above in #640, and noted some design issues there.
