### ISSUE TITLE
Account dropdown changes size for short names

### ISSUE THREAD

**Issue by Lukewh** [canonical-websites/snapcraft.io#612]
Closed:
![screenshot-2018-4-30 my snaps linux software in the snap store](https://user-images.githubusercontent.com/479384/39433545-0d09620e-4c8e-11e8-82ba-abc64eda6543.png)

Open:
![screenshot-2018-4-30 my snaps linux software in the snap store 1](https://user-images.githubusercontent.com/479384/39433559-1199d9c0-4c8e-11e8-84b1-a3e3f4400e1f.png)

**Comment by lyubomir-popov** [comment]
I don't think the menu should match the width of the dropdown. It should be width of name (up to a certain max-width, then truncated with ellipsis) + padding on both sides. Then the dropdown should be right aligned so that the right edge of menu and dropdown coincide, with the left end free to be as wide as needed. 

This will make the menu not align with the keyline of the dropdown menu items, and that's ok.

Would be nice if on mobile the dropdown snaps to full width.

**Comment by therealjuan** [comment]
Fixed on latest vanilla update
