### ISSUE TITLE
Put popularity charts checkboxes in one column

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#669]
From @lyubomir-popov https://github.com/canonical-websites/snapcraft.io/pull/664#issuecomment-389795162

On listing page popularity charts checkboxes should be in one column

**Comment by lyubomir-popov** [comment]
I think it would be better to tighten the vertical spacing between them, rather than using multiple columns. There's a lot of research against mutliptl columns ([one random article](https://baymard.com/blog/avoid-multi-column-forms)). So maybe tight like this?

<img width="310" alt="screen shot 2018-05-18 at 11 47 10" src="https://user-images.githubusercontent.com/2741678/40230981-52b09762-5a91-11e8-9ff4-e7de5495689c.png">

**Comment by lyubomir-popov** [comment]
Agreed to address this once the site is on vanilla 1.7.*

**Comment by Lukewh** [comment]
@bartaz made a valid comment regarding single column here: https://github.com/canonical-websites/snapcraft.io/pull/776#issuecomment-398734616

Any thoughts?

**Comment by lyubomir-popov** [comment]
@Lukewh Replied there.
