### ISSUE TITLE
Slider arrows overlap icons

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-websites/snapcraft.io#830]
### Expected behaviour
Slider arrows should be more subtle and not interfere with the content. This would allow us to keep them visible so it is obvious there's more content in the slider than is visible

### Steps to reproduce the problem
![image](https://user-images.githubusercontent.com/2741678/42087675-cce4a44c-7b8e-11e8-8b3b-90b2c26be6e5.png)

### Specs

- _URL:_
- _Operating system:_
- _Browser:_
<img width="1101" alt="screen shot 2018-06-29 at 10 31 51" src="https://user-images.githubusercontent.com/2741678/42087571-7d3fa298-7b8e-11e8-8683-55e41edc515b.png">

**Comment by Greggless** [comment]
I think It's hard to notice the right-arrow when hovering on a row. This is because:
1. There's a lot of white space when using only 5 tiles
1. The arrow itself being mostly white
1. There is no left-arrow when in the left-most position

I feel like this can be improved by:
1. Using 6 tiles in a row, and/or partially exposing the last one
1. Changing the design of the arrow
1. Having a 'deactivated' state of the arrow

I've had a stab at the overlapping issue:
- reducing the arrow size - 36px 
- changing it's position 
  - Left arrow - centrally aligned to the bottom-left corner of the tile, which moves it outside the grid
  - Right arrow - centrally aligned to the bottom of the tile, but inside the grid
- increasing the snap icon size - 96px


![image](https://user-images.githubusercontent.com/23459065/42267121-1ae3689c-7f70-11e8-8db5-3bb8242cceea.png)

**Comment by anthonydillon** [comment]
Make sure whatever you decide and if successful too propose it to Vanilla.

**Comment by anthonydillon** [comment]
Make sure whatever you decide and if successful too propose it to Vanilla.

**Comment by therealjuan** [comment]
We will rework this as part of the Magazine View.
