### ISSUE TITLE
`support_url` field is deprecated and should not be used as "Developer website"

### ISSUE THREAD

**Issue by cprov** [canonical-websites/snapcraft.io#90]
The store response is currently transitioning from `support_url` to `contact`, which can be a URL or a `mailto:` schema.

More importantly, this field is not supposed to be rendered as "Developer website", but instead as a way to contact the developer when it's needed. The current proposal is to include as many informative links as needed in the description because that gets "linkified".

**Comment by matthewpaulthomas** [comment]
Having a single link that can be either a Web URL or a `mailto:` URL may be convenient for developers in the short term, but I think it would be bad for users. Often they would not realize when the link was `mailto:`, and clicking it would open a mail client unexpectedly.

One solution would be for the snap page to use different link text depending on the protocol, “Developer Web site” or “E-mail the developer”.

In the long term, allowing `mailto:` links may also be a problem for developers, because the snap pages can be crawled by spam address harvesters. So an alternative solution would be for snap pages not to show contact links when they are `mailto:`.

**Comment by matthewpaulthomas** [comment]
[I’ve posted to the Snapcraft forum](https://forum.snapcraft.io/t/url-contact-fields-in-snap-metadata/3067) to discuss this issue further.

**Comment by matthewpaulthomas** [comment]
I’ve made [a URLs proposal](https://forum.snapcraft.io/t/url-contact-fields-in-snap-metadata/3067/6?u=mpt) in the forum thread.

**Comment by carlaberkers** [comment]
Celso's proposed solution works for the short term, we agreed in Caoe Town that a second field will be added. Since this is work for Celso's team, our job is done @matthewpaulthomas :-)
