### ISSUE TITLE
Cropping for snap icons

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#903]
The Snap Store requires a 256x256 icon. Can we let the user crop down to the right size client-side?

**Comment by matthewpaulthomas** [comment]
Agreed with @Greggless. Cropping makes sense for a human’s profile photo, because the camera probably wasn’t positioned with the specific intent of taking a closely-cropped avatar. But an app icon was almost certainly drawn with the correct margins etc to begin with.

It might be useful to offer cropping as a function for [custom header artwork](https://gitlab.gnome.org/GNOME/gnome-software/issues/415), since that’s more likely to come from a photo.

**Comment by bartaz** [comment]
As a first step we could detect the dimensions of the image client-side and warn users before they save/upload it.

Partial solution (that is easier to build then full cropping UI) would be to automatically scale any (square) image larger then 256x256 to correct size. Ideally it could be done on store side, but potentially we could do it on client side as well before saving icon with API.

**Comment by evandandrea** [comment]
>But an app icon was almost certainly drawn with the correct margins etc to begin with.

Yes, the more I think about this the more comfortable I am with closing this issue. My original thinking was that while anyone can open up an image editor and resize or crop, it feels like you're being made to do something that [could easily be done for you](https://stackoverflow.com/questions/37085753/android-studio-image-asset-launcher-icon-background-color). However, I'm not seeing a lot of prior art to support.

**Comment by matthewpaulthomas** [comment]
Thanks @evandandrea. If you find some examples of non-square-proportioned app icons, perhaps report a separate bug for us to transparently letterbox/pillarbox them on upload.
