### ISSUE TITLE
Add classic parameter when installing snaps that requires it

### ISSUE THREAD

**Issue by therealjuan** [canonical-websites/snapcraft.io#928]
When trying to install some snaps `(i.e Go, Asciinema...)` the command line displayed on a Snap details page does not include the relevant parameter needed.

![image](https://user-images.githubusercontent.com/8167677/43134664-aad883c2-8f3a-11e8-9cd2-5c63bcada6ef.png)

**Comment by matthewpaulthomas** [comment]
It may save time to fix [build.snapcraft.io#900](https://github.com/canonical-websites/build.snapcraft.io/issues/900) at the same time as this bug.

**Comment by matthewpaulthomas** [comment]
It’s reasonable to say that it should be more difficult for users to install classic snaps than strict snaps, or that they should be warned first. But omitting the `--classic` in snapcraft.io’s install instructions isn’t an effective way to achieve either of those. This is because for any given snap install action, on average, the person doing the installing is more likely to have found the install instructions somewhere else. And that somewhere else probably _won’t_ omit the `--classic`.

For example with Microsoft PowerShell, [PowerShell’s own instructions](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md#installation-via-snap) include the `--classic`, and so do [MSDN’s](https://blogs.msdn.microsoft.com/powershell/2018/07/20/powershell-core-now-available-as-a-snap-package/), and so do [ZDNet’s](https://www.zdnet.com/article/microsoft-powershell-now-available-on-linux-as-an-ubuntu-snap/), and so do [OMG Ubuntu’s](https://www.omgubuntu.co.uk/2018/07/install-powershell-ubuntu-linux-snap), and so do [Softpedia’s](https://news.softpedia.com/news/microsoft-s-powershell-available-on-ubuntu-as-a-snap-here-s-how-to-install-it-522050.shtml), and so do [BetaNews’s](https://betanews.com/2018/07/20/microsoft-powershell-core-linux-snap/), and every other site I’ve found. It would not be practical to convince all these sites — or, probably, any of them — to remove the `--classic` from their instructions. That is, to convince them to take their instructions for installing a snap, and change them to instructions that don’t install the snap and return an error message instead. Most likely they’d dismiss you as a troll.

(The BetaNews example is instructive: their CMS has unhelpfully munged `--classic` to “–classic”, causing snapd to display the error after all — and the end result is commenters using the error message to generate a conspiracy theory about Microsoft. Unhelpful.)

Further, if the instructions on (most of) those other sites work, but the instructions on snapcraft.io itself return an error instead, it would make us look less competent, which would reflect poorly on the snap platform in general.

If we want to add difficulty and/or scariness, it’s much more practical to do that in snapd itself and in store apps, since there are many fewer of those (and we have far more control of them) than of Web sites.
