### ISSUE TITLE
[Request] Add a way to filter apps per developer on the site

### ISSUE THREAD

**Issue by Skillotic0703** [canonical-websites/snapcraft.io#950]
When you find an interesting application, there's a chance that the developer who created this application had also created other interesting applications so please add a way to filter apps per developer.
Thank you in advance!

**Comment by Lukewh** [comment]
Hi @Skillotic0703,

Thanks for the request! We do have this item on our roadmap but unfortunately, I can't give you an exact timescale of when it'll be implemented.

**Comment by matthewpaulthomas** [comment]
I’ve just checked, and this doesn’t actually seem to be recorded elsewhere. (I don’t find it when searching for “filter”, “search”, “publisher”, or “developer”.) If it is, please link to the original here.

Fixing #328 would make this less important, because then at least searching for a developer name would return too many results rather than too few. It would start to become important again if/when there were individual developers with many snaps. It might be as simple as a filter field on a publisher page (though that isn’t on the roadmap either, so I’ve reported it as #1006).

**Comment by therealjuan** [comment]
We are planning to create some public publisher pages containing some of the most famous publishers we have on the platform. This will be coming in the upcoming weeks.
